# Generated by Django 3.2 on 2023-10-03 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message="Цвет должен быть в формате '#RRGGBB'", regex='^#([A-Fa-f0-9]{6})$')], verbose_name='Цвет тега'),
        ),
    ]
